### ISSUE TITLE
Cant create account due to PIN errors

### ISSUE THREAD

**Issue by lucca65** [cambiatus/improvement-proposals#11]
**Describe the bug**
During the muda tests a user couldn't create account due to the PIN inputs being recognised as empty, even if it had in fact been filled

**To Reproduce**
1. Go to app.cambiatus.io
2. Click on "create account"
3. Fill the form
4. try to create account.

**Expected behavior**
Create account normally.

**Desktop (please complete the following information):**
 - OS: Motoplay G6 Android
 - Browser Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zacck-zz** [comment]
@lucca65  is this still a valid issue even without the custom saitization code?

**Comment by lucca65** [comment]
Fixed already. Closing
