### ISSUE TITLE
12 characters account limitation is game breaker 

### ISSUE THREAD

**Issue by lucca65** [cambiatus/improvement-proposals#13]
**Is your feature request related to a problem? Please describe.**
During tests it became clear that the limitation of 12 characters accounts is a huge thing, a few people literally quit while trying to create an account

**Describe the solution you'd like**
Allow to have premium accounts on our network

**Describe alternatives you've considered**
Add counters and other UX elements to help filling exactly 12 chars

**Additional context**
During Muda pilot, we had several people having a hard time filling those fields.

**Comment by zacck-zz** [comment]
@lucca65  can't we opt out of this in EOS, also we might be able to follow the `Discord` route and allow users to make a username which we can then decorate with some sort of account code ...

**Comment by lucca65** [comment]
closing this for now, as the new login alternatives presented by Natus may change this context entirely!
