### ISSUE TITLE
Add claimer information in the verification list

### ISSUE THREAD

**Issue by lucca65** [cambiatus/improvement-proposals#18]
**Is your feature request related to a problem? Please describe.**
It is clear now that the verification list don't have enough information on it to help the validators to use it.

For example, check the following image:

<img width="1323" alt="Screen Shot 2019-12-08 at 21 45 41" src="https://user-images.githubusercontent.com/1082127/70399579-17d13780-1a04-11ea-8d29-3a74b635ccc9.png">

We have several claims to the same actions, some of those were repeated by the same user, some were false, and some were true. The only way to check those informations is to enter each one of those claims and check one by one.

**Describe the solution you'd like**
We have plenty of space to add more details to it. Like hour, user name and the reward for verifying it.

**Comment by heltonlr** [comment]
@lucca65  In the new dashboard we going to solve this problem, it is in approval and once approved, I will create the task.

**Comment by lucca65** [comment]
Ok, in that case I'll close it for now
