### ISSUE TITLE
Decide on how we should approach the chat feature for now on

### ISSUE THREAD

**Issue by heltonlr** [cambiatus/improvement-proposals#19]
After fundes stopped using the chat, we don't do maintenance on it. As a result some users get confused on a button that does not work. We should think on how we are going to approach this feature for now on. Muda community uses it and we need better ways to handle that for now on

**Comment by lucca65** [comment]
nice @zacck. @heltonlr how do you think we should approach this? 

I was thinking about questions, instead of a chat, maybe a private inbox too.... Not sure!

**Comment by zacck-zz** [comment]
@lucca65  I think we need to decide which places chat is available from, Is it only just shop? or are there other places user can chat from ?
Do we only have p2p chat or is there group discussions at some point 

On the implementation side, since we have sockets working I have a sweet chat implementation that can work with our stack really nice and it will be completely native..

**Comment by lucca65** [comment]
sounds good for me @zacck but I think we need to check with @heltonlr first to see what type of UX we are going to provide for the users.

**Comment by zacck-zz** [comment]
@lucca65  I agree  ...

**Comment by heltonlr** [comment]
Sounds good for me, do you will need interface for this @zacck? But in the meantime let's remove the button and align the interface.

**Comment by lucca65** [comment]
@heltonlr sure we will but first we should decide on what type of interaction we will need

For now we have this to remove the button: https://github.com/cambiatus/frontend/issues/110

Lets keep de discussion here

**Comment by flaviagoma** [comment]
Hello guys, I fell great being here!! Just finished my first Github tutorial, now I know what a commit is and how to create a branch and a pull request  :D

So, I wonder how the discussion about the ask button is going. My personal opinion is that for starters it should be a p2p space for clarifications about the offers at the store. And maybe an email could be sent as a notification that a message was receive at the platform. 

I will also talk about it with our Muda partners and I will gladly assist in being this bridge between you guys.

**Comment by zacck-zz** [comment]
@flaviagoma  welcome! and congratulations!

For sure having a p2p space for clarifications is a good way to introduce chat and for sure we can do email notifications and also push notifications such as those you get from popular applications

**Comment by flaviagoma** [comment]
Hello @zacck, thank you! 😁
Perhaps a notification directly on the mobile would be even better...

**Comment by zacck-zz** [comment]
Some parts of our system already do that, it should be reasonable to achieve for us ..

**Comment by lucca65** [comment]
Guess this is on hold since December and no clients are using or requiring this for now. Some suggestions include adding WhatsApp integration to open chats directly. Anyway we will not be doing chat directly anymore! I'm closing this
