### ISSUE TITLE
Allow objective conclusion

### ISSUE THREAD

**Issue by lucca65** [cambiatus/improvement-proposals#27]
**Is your feature request related to a problem? Please describe.**
There is no way to set an objective and its child action as completed

**Describe the solution you'd like**
Allow a button or something that sets an objective and its children actions as completed

**Comment by heltonlr** [comment]
hey @lucca65 , this functionality will change some elements in the interface (Objectives and Actions), I going to work in that today.

**The flow in Figma:**
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=116%3A9387

**Comment by heltonlr** [comment]
Finished Team, Let me know if you have any questions;

https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=116%3A9387

Some points:

- If an objective is marked as complete, all your actions are marked as complete and can't be edited.

**Comment by heltonlr** [comment]
team, i forgot to put the mobile interfaces. Working in that now.

**Comment by heltonlr** [comment]
> team, i forgot to put the mobile interfaces. Working in that now.

**Done**
https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=153%3A2503

**Comment by lucca65** [comment]
this will require a change in the contract/eventsource/backend and frontend to allow the objective to have a title and a description

**Comment by heltonlr** [comment]
> this will require a change in the contract/eventsource/backend and frontend to allow the objective to have a title and a description

We currently only have a title, correct? No problem, we can remove the description. I thought you had

**Comment by lucca65** [comment]
No we don't but I do think it is a good addition. We have this idea of allowing users to set a Good and a Great option to know that the objectives were completed, good being the minimum and great being the "extra". Maybe is there a way for us to add questions to the form, that would become a text?

Maybe something like:

"What would be a good measure of completion for this objective?"

The user fill this input

"What would be a great measure? A indicative that the community did great!"

the user fill this input


What are your thoughts @heltonlr 

@zacck do you have any inputs for that? This is from the Value based Thinking we were talking earlier in the week

**Comment by zacck-zz** [comment]
Hey @lucca65 @heltonr let me have a think and do some trials will comment
on this soon with views

**Comment by heltonlr** [comment]
The idea sounds good @lucca65. I would like to suggest a meeting  for more details about this. Can you talk tomorrow?

**Comment by lucca65** [comment]
let’s schedule this meeting in slack folks

**Comment by lucca65** [comment]
we also have a frontend related task for this: https://github.com/cambiatus/frontend/issues/169

**Comment by lucca65** [comment]
Thanks @heltonlr we have everything we need to begin

**Comment by lucca65** [comment]
This is already implemented on the backend and its being implemented with the help of @marcjal! I'll close this as we are really close to finishing it!
