### ISSUE TITLE
Allow decimal number in transactions

### ISSUE THREAD

**Issue by natillasol** [cambiatus/improvement-proposals#28]
**Is your feature request related to a problem? Please describe.**
Currently the app doe not allow decimal numbers in transactions.  

**Describe the solution you'd like**
Allow for decimal numbers. This may be useful in trading small objects. 

**Additional context**
<img width="338" alt="Screen Shot 2020-02-25 at 13 37 21" src="https://user-images.githubusercontent.com/57719975/75281162-5e992700-57d4-11ea-908d-3c2fc140b2f2.png">

**Comment by lucca65** [comment]
its now supported as well!
