### ISSUE TITLE
Intermittent Issue when Approving or Disapproving actions in the Muda enviroment

### ISSUE THREAD

**Issue by zacck-zz** [cambiatus/improvement-proposals#29]
**Describe the bug**
Xavier from Muda has an intermittent issue where when he tries to approve or disapprove an action that his to verify it fails with  a not allowed error.

Ideally he should be able to approve or disapprove actions where is a verifier 

**To Reproduce**
- Open Muda Env
- Open the second objective
- Try to approve the single action

**Expected behavior**
A verifier should be able to approve or disapprove an action with voting counts.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

**Smartphone (please complete the following information):**
 N/A

**Comment by lucca65** [comment]
solved simply by updating event-source on production
