### ISSUE TITLE
Add expiration date to the Shop

### ISSUE THREAD

**Issue by lucca65** [cambiatus/improvement-proposals#34]
**Is your feature request related to a problem? Please describe.**
Users sometimes lost their account keys or simply stay a lot of time without entering the app and their sales may become stale or totally out of context. We should implement a way for sales to be temporary, effectively making all sales active at a certain extend.

**Describe the solution you'd like**
Add expiration date to all sales, given a time to live that the community can configure

**Describe alternatives you've considered**
If at least we had a way to make the admin be allowed to disable certain sales, it would be enough

**Additional context**

**Comment by lucca65** [comment]
@heltonlr do you have any ideas on this? This happened today with a user from muda, check it out:

<img width="450" alt="Screen Shot 2020-07-27 at 23 12 03" src="https://user-images.githubusercontent.com/1082127/88611044-9693e700-d05e-11ea-9832-5242d69f99ed.png">

**Comment by heltonlr** [comment]
I think these cases going to resolve when we create the new shop's interfaces with the seller's contact and communication by email. We can suggest the buyers contact the sellers first.

Maybe the Shop must be the first on prioritization queue after Ticolones.

**Comment by lucca65** [comment]
Hmm I see. Ok I trust your judgement on this! I'll close the issue then
