### ISSUE TITLE
Polkadot Blockchain Research

### ISSUE THREAD

**Issue by victorgdev** [cambiatus/improvement-proposals#38]
**Is your feature request related to a problem? Please describe.**
NO

**Describe the solution you'd like**
New blockchain option

**Describe alternatives you've considered**

The Polkadot blockchain is a multi-chain environment where cross-chain registries and cross-chain computation are possible. What that means is that, Polkadot creates an unique blockchain ecosystem that allows arbitrary data (not just tokens) to be transferred across blockchains (public, open, permissionless and private, permissioned) through smart-contract. 

<img src="https://polkadot.network/assets/img/logo-polkadot.svg?v=0e537d78ef" width="150">

### 0. Table of Contents

- Overview
- Technology
- More information

### 1. Overview

**Popular specs:**

- **Speed** 
-- Block time: six seconds and most transactions are considered final after less than a minute. This makes it ideal for building applications where speed is critical — like decentralized exchange (DEX) platforms. 

- **Scalability** 
-- Currently: more than 1,000 transactions per second (tps) 
-- Goal: 1 million tps, with the use of sharding and optimized parachains. 

- **Interoperability** applications built on Polkadot and its parachains can easily interact with those on other blockchains (including Ethereum). Producing the first interoperable DeFi ecosystem. 

**1.1. Why**
 
Polkadot creates an ecosystem that enables a Web where identity and data are owned by its users and safely secured form any central authority via a decentralized chain of chains environment. 

In other words, it is built to connect all kinds of chains (private, public etc) facilitating an ecosystem Web where independent blockchains can exchange information and transactions in a trustless way.

**1.2. What** 

Polkadot enables scalability by allowing blockchains to communicate with each other in a secure, trust-free environment (info/data exchange under common security guarantees).

The core pillars of the Polkadot network are: governance, upgradability, and interopability, which generates the needed flexibility while mitigates risks of network forks.

**1.3. How**

Polkadot connects a network of heterogeneous blockchains (parachains and parathreads), which connects to and are secured by a specific chain (Polkadot Relay Chain). They can also connect with external networks via bridges (Ex. Ethereum, Bitcoin etc).

The Polkadot network is based on the [sharded model](https://en.wikipedia.org/wiki/Shard_(database_architecture)) for database architecture. This model is, in short, to separate a shard or horizontal data partition in different database servers to spread load (Ex. separating rows of a database table in different servers). In the Polkadot ecosystem this architecture enables parallel transaction processing.

**Basic Structure of the Polkadot network:**

- Polkadot Architecture
-- [Video](https://youtu.be/xBfC6uTjvbM)
-- [Documentation](https://wiki.polkadot.network/docs/en/learn-architecture)

**A. Relay Chain**

Called the heart of the whole ecosystem, this chain is responsible for ensuring the shared security, governance (consensus) and cross-chain interop.

Based on Polkadot's design, as long as a chain's logic can compile to Wasm and adheres to the Relay Chain API, then it can connect to the Polkadot network as a parachain.

Polkadot has a Relay Chain acting as the main chain of the system. Parachains construct and propose blocks to validators on the Relay Chain, where the blocks undergo rigorous availability and validity checks before being added to the finalized chain. As the Relay Chain provides the security guarantees, collators - full nodes of these parachains - don't have any security responsibilities, and thus do not require a robust incentive system. This is how the entire network stays up to date with the many transactions that take place.

The  allows parachains to send messages of any type to each other. The shared security and validation logic of the Relay Chain provide the environment for trust-free message passing that opens up true interoperability.

**B. [Parachains](https://wiki.polkadot.network/docs/en/learn-parachains)**

Sovereign blockchains that can/are:
- Have their own tokens.
- Develop theis specific functionalities based off custom use cases.
- To enable the horizontal partitioning database design (sharded model) 
- To allow for parallel transaction processing (multiple transactions occurring in parallel as opose to sequentially).
- Has a unique state transition function (STF).
- Needed to compile to Wasm and adheres to the Relay chain API to connect to the heart of the network (Polkadot Relay chain).
- To enable cross-registries communication via [Cross-Chain Messaging Protocol (XCMP)](https://wiki.polkadot.network/docs/en/learn-crosschain)

**C. [Parathreads](https://wiki.polkadot.network/docs/en/learn-parathreads)**

**Same thing as the parachains**, but created to/for:
- Have a pay-as-you-go model available in the ecosystem.
- Best business option for blockchains that don't need continuous connectivity to the ecosystem

**D. [Bridges](https://wiki.polkadot.network/docs/en/learn-bridges)**

Allows true interop (connection and communication) between parachains and parathreads to external networks. 

Basically, these (bridge parachains](https://wiki.polkadot.network/docs/en/learn-bridges) offer two-way compatibility between the Polkadot ecosystem and the external world. 

For instance, imagine the Polkadot network interop with external blockchains such as Bitcoin, Ethereum, or Tezos (among others) via [XCMP](https://wiki.polkadot.network/docs/en/learn-crosschain). 

**E. [Smart Contracts](https://wiki.polkadot.network/docs/en/build-smart-contracts#docsNav)**

[Here](https://www.youtube.com/watch?v=fKHkFBXaUxQ&ab_channel=Polkadot) is a video explaining the smart contract situation on Polkadot and Kusama.

Basically, the Polkadot Relay Chain will not support smart contracts natively. However, parachains on Polkadot will support smart contracts. Here are some projects that allow for the use of smart contracts:

- [Edgeware](https://edgewa.re/)
- Substrate built-in [contract pallet](https://substrate.dev/rustdocs/v2.0.1/pallet_contracts/index.html)
- EVM pallet which lets a parachain implement the Ethereum Virtual Machine, thereby supporting almost direct ports of Ethereum contracts. 
- [Moonbeam](https://moonbeam.network/) and [Frontier](https://github.com/paritytech/frontier).

### 2. Technology
<img src="https://polkadot.network/assets/img/dg-stack.svg?v=0e537d78ef" width="300">

- Relay chain is built with [Substrate](https://www.substrate.io/) (blockchain-building framework).
- State machine is compiled to WebAssembly (Wasm).
- Networking uses libp2p (flexible cross-platform network framework for peer-to-peer applications).
- Runtime environment is being coded in Rust, C++, and Golang.

Here are the [builder Tools](https://wiki.polkadot.network/docs/en/build-tools-index)

### 3. More Information

- [Join the community](https://polkadot.network/community/)
- Tech Papers for reading:
-- [Lightpaper](https://polkadot.network/Polkadot-lightpaper.pdf)
-- [Whitepaper](https://polkadot.network/PolkaDotPaper.pdf)
- [Beginner Friendly Explanation Video](https://www.youtube.com/watch?v=_-k0xkooSlA&ab_channel=Polkadot)
- Grants options (are from Web3 Foundation):
-- [General Grants Program](https://github.com/w3f/General-Grants-Program) funding up to U$D 100,000
-- [Open Grants Program](https://github.com/w3f/Open-Grants-Program) funding up to U$D 30,000
- [Polkadot Decoded Event](https://decoded.polkadot.network/2021submission) to submit ideas for a presentations or workshop to be voted on by the community

**Comment by lucca65** [comment]
closed in favor of a discussion in the contract repository: https://github.com/cambiatus/contracts/discussions/37
