### ISSUE TITLE
Cardano Blockchain - Smart Contract Research

### ISSUE THREAD

**Issue by victorgdev** [cambiatus/improvement-proposals#39]
**Is your feature request related to a problem? Please describe.**
N/A

**Describe the solution you'd like**
Blockchain technology

**Describe alternatives you've considered**

**Additional context**
This is a simplified research about Smart Contracts in the Cardano blockchain. For a quick video introduction of the Cardano blockchain technology please watch this [video](https://www.youtube.com/watch?v=Do8rHvr65ZA&ab_channel=SimplyExplained)

On Cardano, smart contracts and DApps will be enabled through the Plutus Platform, and for financial contracts, the Marlowe domain specific language (DSL).

**Plutus Platform** 

The Plutus Platform will empower smart contract authors to easily write and deploy smart contracts and build DApps. The Plutus Platform includes the Plutus Haskell software development kit (SDK), which will include libraries and development tooling for writing smart contract applications in Haskell. Smart contracts written on the Plutus Platform will contain the logic, that will eventually allow them to run on Plutus Core, deployable on the Cardano blockchain.

- [video](https://www.youtube.com/watch?v=usMPt8KpBeI&ab_channel=IOHK)
- Good reading about [Plutus](https://iohk.io/en/blog/posts/2019/07/31/secure-smart-contracts-with-the-plutus-ebook/)
- [Functional Smart Contracts on Cardano](https://www.youtube.com/watch?v=MpWeg6Fg0t8&ab_channel=IOHK) video

 **Marlowe**

Another option is Marlowe, which is a language for modeling financial instruments as smart contracts on a blockchain. It is a simple domain-specific language (DSL), which comprises a small number of powerful building blocks that can be assembled into expressive financial contracts. It is embedded in the Haskell language, which has its own established ecosystem and testing framework. 
You do not need programming expertise to use Marlowe and you can explore your Marlowe financial constructions with a browser-based contract editor and simulator. 

Basic features for Marlowe are:
- Analyze contracts without having to run them
- Check behavior through simulation
- Describe financial agreements on the blockchain

List of resources for Marlowe:
- [video](https://www.youtube.com/watch?v=pRfdST1yjPs&ab_channel=CardanoSense)
- [Playground](https://alpha.marlowe.iohkdev.io/#/simulation)
- [Editor](https://alpha.marlowe.iohkdev.io/#/blockly)

**Reading**
- [Cardano Smart Contracts](https://forum.cardano.org/t/cardano-smart-contracts/29580)
- [An Introduction to DApps and Smart Contracts](https://forum.cardano.org/t/an-introduction-to-decentralized-applications-and-smart-contracts/40778)
- [About Cardano Smart Contracts - A compilation of Contents and Resources](https://forum.cardano.org/t/about-cardano-smart-contracts-a-compilation-of-contents-and-resources/40260)
- [Contracts can be smarter on Cardano](https://forum.cardano.org/t/contracts-can-be-smarter-on-cardano/42692)
- [Cardano Forum](https://forum.cardano.org/)

**Comment by lucca65** [comment]
moved to a discussion on our contract repo: https://github.com/cambiatus/contracts/discussions/36
