### ISSUE TITLE
Improve analysis page

### ISSUE THREAD

**Issue by lucca65** [cambiatus/improvement-proposals#40]
**Is your feature request related to a problem? Please describe.**
Some communities have a lot of engagement and the analysis page is inefficient to handle a large number of claims. Here is a list of improvements. Those improvements aim to fix the problem of old claims staying in a limbo and to also make the validator workflow more efficient.

**Describe the solution you'd like**

- [x] - Save filters and pagination on the query string so its possible to go back to where it was after page changing
- [x] - Allow hovering to show more details about the profile
- [x] - Allow hovering to show more details on a single claim (maybe have a collapsable section?)
- [x] - Show voting status (maybe a progress bar?) so its easy to know how many positive/negative votes we already have and how many it need.
- [x] - Add ordering filter, defaulting to old first
- [x] - Group similar claims (User claimed this action X times in the last 7 days)

**Describe alternatives you've considered**
N/A

**Additional context**
Muda requested this but this surely is a bottleneck in the whole Cambiatus Ecosystem

**Comment by lucca65** [comment]
@heltonlr can you provide screens to allow for those features?

**Comment by heltonlr** [comment]
> @heltonlr can you provide screens to allow for those features?

Certainly @lucca65, right now, there are other high priorities in the design team.  But I will check and send you a date

**Comment by lucca65** [comment]
don't worry @heltonlr its async, this repo is only for us to gather discussion points and keep in mind big features! 💪

**Comment by heltonlr** [comment]
> don't worry @heltonlr its async, this repo is only for us to gather discussion points and keep in mind big features! 💪

Good, probably @rafachadud will take that task after Cambiuu’s website.

**Comment by lucca65** [comment]
hey folks, let me know when you have news about this!

**Comment by heltonlr** [comment]
Hey @lucca65 , we don't begin yet. May we can talk about it at the prioritization meeting.

**Comment by heltonlr** [comment]
"Allow hovering to show more details on a single claim (maybe have a collapsable section?)"

@lucca65 About this item, which "details" you heard the user speaking?

**Comment by lucca65** [comment]
Mainly voting and time since it was opened. Maybe we can show a progress bar? or a little text saying no one voted yet? 

Some text with "opened 3 days ago" or something like this

**Comment by heltonlr** [comment]
_"Group similar claims (User claimed this action X times in the last 7 days)"_

This one is complex, I think it’s worth talking to Karla. I'll try to take something on Thursday

**Comment by lucca65** [comment]
yeah, this is also one that we've talked about on the past. I still see this one as a complex feature, requiring both backend and frontend work. 

But, the recommendations described on these issues are super simple and straight forward, we already have all that information available, we just don't display it really.

I we should address this "claiming x times" thing in a separate issue, because for sure it would take more time to do than everything else on this list together
