### ISSUE TITLE
Celebrate and review completed objectives

### ISSUE THREAD

**Issue by henriquecbuss** [cambiatus/improvement-proposals#44]
**Is your feature request related to a problem? Please describe.**
The main goal of a community in Cambiatus is to complete objectives, which are a collection of actions. Right now, that importance is only in our heads, and it's not communicated through our app.

**Describe the solution you'd like**
Celebrate in some way when a community completes an objective, by showing an animation, a special screen, something like that. We could also have some statistics on that objective, such as how many actions it took to complete, etc. Similarly, we could have statistics on all completed objectives as a whole (how many objectives have been completed, how much currency they've generated, etc.)

**Describe alternatives you've considered**
We were discussing some of the ways to do some of this on cambiatus/frontend#524, there are some comments and discussions there about this issue.

**Additional context**
Has been talked about on cambiatus/frontend#524. Here are some good points from that issue:

- Completing an objective should be something special for the community. There should be some sort of celebration when it happens (and we should probably make it clearer throughout the app that this is an important thing). Right now, you just click a button and pretty much nothing happens.
- The objectives page is pretty old, and might be confusing for some people.

@lucca65 also mentioned some good-to-have things:
- History of completed objectives
- Ability to have a revision text when completing an objective (and showing it on the history of completed objectives)
- Statistics about the objective: interactions (open claims), engagement(number of users who were approved), failures or frauds (number of users who were disapproved), number of approved claims, number of disapproved claims, number of pending claims after the objective has been completed.

**Comment by lucca65** [comment]
Thanks for this @NeoVier 

@muguika we would love your ideas here!

**Comment by muguika** [comment]
"Completing an objective should be something special for the community."  loved this 
I think the idea of having the "statistics about the objective" is fantastic, a way to show the history of the community and the achievements they have made thanks to their currency. I can see this like moving the objective from the top part to the bottom of the community page, adding a card below the current community numbers we have there.

**Comment by henriquecbuss** [comment]
@rafachadud made a nice screen + animation to show when an objective is completed! Here's the figma link: https://www.figma.com/file/nEPG6Dkns8hDVCudVUTEzc/Dashboard?node-id=2877%3A10267

**Comment by lucca65** [comment]
closing as this will be addressed on the frontend
