### ISSUE TITLE
Add auto reload to sale creation

### ISSUE THREAD

**Issue by lucca65** [cambiatus/improvement-proposals#5]
**Is your feature request related to a problem? Please describe.**
When creating a new sale, after the submit we are redirected to the main shop screen. Where our newly created sale don't exist yet!

**Describe the solution you'd like**
Similar to what we had on the community creation process we need to make sure the screen only reloads after the transaction has been sent to the blockchain and confirmed by our backend.

**Describe alternatives you've considered**
We already have a pattern on doing this. Check additional context

**Additional context**
Backend implementation of this: https://github.com/cambiatus/backend/pull/10/files
Frontend implementation: https://github.com/cambiatus/frontend/pull/29

**Comment by zacck-zz** [comment]
Oh this is also affected by #8

**Comment by lucca65** [comment]
This will be addressed by #8
