### ISSUE TITLE
Allow several images on the shop

### ISSUE THREAD

**Issue by lucca65** [cambiatus/improvement-proposals#7]
**Is your feature request related to a problem? Please describe.**
Right now we only allow one image in a sale. We need to allow more to follow the design for that screen

**Describe the solution you'd like**
Modify the smart contract to have a table with several images into it, those images will be IPFS hashes.

**Describe alternatives you've considered**
We could also do:

1) Add several columns to the `sale` table such as `image1` `image2` `image3`.

2) Have it all in one field, splitting the hashes using `-`, `,` or some other separator

3) Do it all off chain. It can be tricky as we need to be 100% sure the backend ID is in sync with the blockchain ID

**Additional context**
EOSIO has some limitations on data size, we need to work around those

**Comment by zacck-zz** [comment]
@lucca65  if we go to s3 we can use the sale id to associate the images with the sale item and all this can be done async ....

**Comment by lucca65** [comment]
We should probably just finish migrating to IPFS and adding auto reload to the shop (#5) and make it a 100% graphql mutation query. Add several pictures using our backend alone

**Comment by lucca65** [comment]
We will do this using a full GraphQL API, after implementing authentication fully. Closing this as this is already being addressed on frontend and backend
